name: Clippy Check
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  clippycheck:
    name: Clippy Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout
      - uses: arduino/setup-protoc@v1
        name: Install protoc
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions-rs/toolchain@v1
        name: Install Rust toolchain
        with:
          toolchain: stable
          components: clippy
          override: true
      - uses: actions-rs/clippy-check@v1
        name: Run Clippy
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features